import { ZodType } from 'zod'

import {
  EntityGlobalIndexHashKeyValue,
  EntityGlobalIndexRangeKeyValue,
  EntityHashKeyValue,
  EntityLocalIndexRangeKeyValue,
  EntityRangeKeyValue,
  GlobalIndexName,
  LocalIndexName
} from './EntityKey'
import { KeyFieldPath, PickByPaths } from './FieldPath'
import { Table } from './Table'
import { Prettify } from './utils'

/**
 * Defines how to construct a key part (hash or range) from entity fields.
 *
 */
type KeyPartDefinition<TItem, TKeyFields extends readonly KeyFieldPath<TItem>[], TResult> = {
  fields: TKeyFields
  calculate: (item: PickByPaths<TItem, TKeyFields[number]>) => TResult
}

/**
 * Type definition for local secondary index configurations on an Entity.
 *
 * Local indexes share the table's hash key but use a different range key.
 * Each index requires a rangeKey definition specifying fields and calculation logic.
 *
 * @template TTable - The table configuration
 * @template TSchema - The entity's Zod schema
 * @template TLocalIndexRangeKeyFields - Map of index names to their range key field paths
 */
export type EntityLocalIndexesDefinition<
  TTable extends Table<any>,
  TItem,
  TLocalIndexRangeKeyFields extends Partial<
    Record<LocalIndexName<TTable>, readonly KeyFieldPath<TItem>[]>
  >
> = {
  [K in keyof TLocalIndexRangeKeyFields]: {
    rangeKey: KeyPartDefinition<
      TItem,
      Exclude<TLocalIndexRangeKeyFields[K], undefined>,
      EntityLocalIndexRangeKeyValue<TTable, Extract<K, LocalIndexName<TTable>>>
    >
  }
}

/**
 * Type definition for global secondary index configurations on an Entity.
 *
 * Global indexes have their own hash and optional range keys, independent
 * from the table's primary index. Each index requires field mappings and
 * calculation logic.
 *
 * @template TTable - The table configuration
 * @template TSchema - The entity's Zod schema
 */
export type EntityGlobalIndexesDefinition<TTable extends Table<any>, TItem> = {
  [K in GlobalIndexName<TTable>]?: {
    hashKey: KeyPartDefinition<
      TItem,
      readonly KeyFieldPath<TItem>[],
      EntityGlobalIndexHashKeyValue<TTable, Extract<K, GlobalIndexName<TTable>>>
    >
  } & (TTable['globalIndexes'] extends Record<string, any>
    ? TTable['globalIndexes'][Extract<K, GlobalIndexName<TTable>>]['rangeKey'] extends string
      ? {
          rangeKey: KeyPartDefinition<
            TItem,
            readonly KeyFieldPath<TItem>[],
            EntityGlobalIndexRangeKeyValue<TTable, Extract<K, GlobalIndexName<TTable>>>
          >
        }
      : { rangeKey?: never }
    : { rangeKey?: never })
}

type EntityLocalIndexesOption<
  TTable extends Table<any>,
  TItem,
  TLocalIndexRangeKeyFields extends Partial<
    Record<LocalIndexName<TTable>, readonly KeyFieldPath<TItem>[]>
  >
> =
  LocalIndexName<TTable> extends never
    ? never
    : EntityLocalIndexesDefinition<TTable, TItem, TLocalIndexRangeKeyFields>

/**
 * Represents a strictly typed entity bound to a specific DynamoDB table.
 *
 * This type captures:
 * - The Zod schema for runtime validation and type inference
 * - The table configuration to ensure key conformance
 * - The key calculation logic
 */
export interface Entity<
  TTable extends Table<any>,
  TName extends string,
  TItem,
  THashKeyFields extends readonly KeyFieldPath<TItem>[],
  TRangeKeyFields extends readonly KeyFieldPath<TItem>[],
  TGlobalIndexes extends Partial<Record<GlobalIndexName<TTable>, any>>,
  TLocalIndexRangeKeyFields extends Partial<
    Record<LocalIndexName<TTable>, readonly KeyFieldPath<TItem>[]>
  >,
  TTtl extends ((domain: TItem) => number | undefined) | undefined,
  TEntityType extends string | undefined,
  TTransform = undefined,
  TInput = TItem
> {
  name: TName
  table: TTable
  schema: ZodType<TItem, any, TInput>
  key: {
    hashKey: KeyPartDefinition<TItem, THashKeyFields, EntityHashKeyValue<TTable>>
  } & (TTable['primaryIndex']['rangeKey'] extends string
    ? { rangeKey: KeyPartDefinition<TItem, TRangeKeyFields, EntityRangeKeyValue<TTable>> }
    : { rangeKey?: never })
  globalIndexes?: TGlobalIndexes
  localIndexes?: EntityLocalIndexesDefinition<TTable, TItem, TLocalIndexRangeKeyFields>
  entityType: TEntityType
  ttl?: TTable['ttl'] extends keyof TTable['fields'] ? TTtl : never
  transform?: TTransform
}

/**
 * Definition for bidirectional data transformation.
 *
 * @template TExternal - The external type (inferred from schema)
 * @template TGeneratedFields - Internal fields generated by zodynamo (keys, ttl, etc.)
 * @template TInternal - The internal type stored in DynamoDB
 */
export type EntityTransform<TExternal, TGeneratedFields, TInternal> = {
  encode: (input: Prettify<TExternal & TGeneratedFields>) => TInternal
  decode: (input: TInternal) => TExternal
}
